include("./relief_test.jl")
include("./relieff_test.jl")
include("./reliefseq_test.jl")
include("./surf_test.jl")
include("./surfstar_test.jl")
include("./multisurfstar_test.jl")
include("./multisurf_test.jl")
include("./reliefmss_test.jl")
include("./boostedsurf_test.jl")
include("./swrfstar_test.jl")
include("./turf_test.jl")
include("./vlsrelief_test.jl")
include("./iterative_relief_test.jl")
include("./irelief_test.jl")
include("./ecrelief_test.jl ")
